/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 24-Oct-2022 15:43:18
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 32
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
const int BL = 32;
const real64_T B[32] = {
   -0.02707022966447, -0.02987522024093,  -0.0307263576717, -0.02921143720744,
   -0.02507061996854, -0.01823010610981,-0.008821472042451, 0.002815714843191,
    0.01614893298785,  0.03048473507951,  0.04501553790084,  0.05887754335194,
    0.07121506810082,  0.08124588465352,    0.088321990343,  0.09198054693989,
    0.09198054693989,    0.088321990343,  0.08124588465352,  0.07121506810082,
    0.05887754335194,  0.04501553790084,  0.03048473507951,  0.01614893298785,
   0.002815714843191,-0.008821472042451, -0.01823010610981, -0.02507061996854,
   -0.02921143720744,  -0.0307263576717, -0.02987522024093, -0.02707022966447
};
