/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 24-Oct-2022 16:26:24
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 32
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
const int BL = 32;
const real64_T B[32] = {
    0.01586973020855, -0.02001783677786, -0.02428382646759,  0.02860889716013,
    0.03293120886419, -0.03718704840262, -0.04131205778646,  0.04524249876178,
    0.04891652478868, -0.05227543120271,  -0.0552648545357,  0.05783589293569,
    0.05994612130494,  -0.0615604771294, -0.06265199594641,  0.06320237891383,
    0.06320237891383, -0.06265199594641,  -0.0615604771294,  0.05994612130494,
    0.05783589293569,  -0.0552648545357, -0.05227543120271,  0.04891652478868,
    0.04524249876178, -0.04131205778646, -0.03718704840262,  0.03293120886419,
    0.02860889716013, -0.02428382646759, -0.02001783677786,  0.01586973020855
};
